version: '3.0'
services:
  
  sales_postgres:
    image: postgres
    restart: always
    container_name: sales_postgres
    environment:
      - POSTGRES_USER=sales
      - POSTGRES_PASSWORD=sales
    ports: 
      - '5432:5432'
    volumes:
      - ../postgre/db:/var/lib/postgresql/data



    